apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-frame-deployment
  labels:
    app: eks-frame-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-frame-app
  template:
    metadata:
      labels:
        app: eks-frame-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - name: eks-frame-app
          image: 345124661122.dkr.ecr.us-east-1.amazonaws.com/frame-persistence:latest
          ports:
            - name: http
              containerPort: 8080
          env:
#            - name: example
#              value: example
          readinessProbe:
            httpGet:
              path: /api/v1/actuator/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/actuator/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 10
          resources:
            requests:
              cpu: 500m
              memory: 1024Mi
            limits:
              cpu: 2000m
              memory: 2048Mi
          imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux